export const palette = {
  white: "#FFFFFF",
  black: "#000000",
  slate: {
    50: "#F8FAFC",
    100: "#F1F5F9",
    200: "#E2E8F0",
    300: "#CBD5E1",
    400: "#94A3B8",
    500: "#64748B",
    600: "#475569",
    700: "#334155",
    800: "#1E293B",
    900: "#0F172A",
    950: "#020617",
  },
  blue: {
    50: "#EFF6FF",
    100: "#DBEAFE",
    200: "#BFDBFE",
    500: "#3B82F6",
    600: "#2563EB",
    700: "#1D4ED8",
    800: "#1E40AF",
    900: "#1E3A8A",
  },
  teal: {
    50: "#F0FDFA",
    100: "#CCFBF1",
    500: "#14B8A6",
    600: "#0D9488",
    700: "#0F766E",
  },
  green: {
    50: "#F0FDF4",
    100: "#DCFCE7",
    600: "#16A34A",
    700: "#15803D",
  },
  amber: {
    50: "#FFFBEB",
    100: "#FEF3C7",
    500: "#F59E0B",
    700: "#B45309",
  },
  red: {
    50: "#FEF2F2",
    100: "#FEE2E2",
    600: "#DC2626",
    700: "#B91C1C",
  },
  violet: {
    50: "#F5F3FF",
    100: "#EDE9FE",
    600: "#7C3AED",
    700: "#6D28D9",
  },
} as const;

export const colors = {
  background: {
    app: "#F6FAFF",
    canvas: "#F8FAFC",
    surface: palette.white,
    surfaceRaised: "#FCFEFF",
    subtle: palette.blue[50],
    inverse: palette.slate[950],
  },
  text: {
    primary: palette.slate[900],
    secondary: palette.slate[700],
    muted: palette.slate[500],
    inverse: palette.white,
    link: palette.blue[700],
    danger: palette.red[700],
    success: palette.green[700],
  },
  border: {
    default: palette.slate[200],
    strong: palette.slate[300],
    focus: palette.blue[500],
    danger: palette.red[600],
    success: palette.green[600],
    warning: palette.amber[500],
  },
  action: {
    primary: {
      background: palette.blue[700],
      pressed: palette.blue[800],
      foreground: palette.white,
      disabledBackground: palette.slate[300],
      disabledForeground: palette.slate[600],
    },
    secondary: {
      background: palette.white,
      pressed: palette.blue[50],
      foreground: palette.blue[800],
      border: palette.blue[200],
      disabledBackground: palette.slate[100],
      disabledForeground: palette.slate[500],
    },
    ghost: {
      background: "transparent",
      pressed: palette.slate[100],
      foreground: palette.slate[800],
      disabledForeground: palette.slate[400],
    },
    danger: {
      background: palette.red[600],
      pressed: palette.red[700],
      foreground: palette.white,
      disabledBackground: palette.red[100],
      disabledForeground: palette.red[700],
    },
  },
  feedback: {
    info: {
      background: palette.blue[50],
      border: palette.blue[100],
      pressed: palette.blue[100],
      text: palette.blue[900],
      icon: palette.blue[700],
    },
    success: {
      background: palette.green[50],
      border: palette.green[100],
      pressed: palette.green[100],
      text: palette.green[700],
      icon: palette.green[600],
    },
    warning: {
      background: palette.amber[50],
      border: palette.amber[100],
      pressed: palette.amber[100],
      text: palette.amber[700],
      icon: palette.amber[500],
    },
    error: {
      background: palette.red[50],
      border: palette.red[100],
      pressed: palette.red[100],
      text: palette.red[700],
      icon: palette.red[600],
    },
    neutral: {
      background: palette.slate[50],
      border: palette.slate[200],
      pressed: palette.slate[100],
      text: palette.slate[700],
      icon: palette.slate[500],
    },
  },
  gradeBand: {
    elementary: {
      background: "#F0FDFA",
      surface: "#FFFFFF",
      accent: palette.teal[500],
      accentStrong: palette.teal[700],
      text: palette.slate[900],
    },
    middle: {
      background: "#EFF6FF",
      surface: "#FFFFFF",
      accent: palette.blue[600],
      accentStrong: palette.blue[800],
      text: palette.slate[900],
    },
    high: {
      background: "#F8FAFC",
      surface: "#FFFFFF",
      accent: palette.slate[800],
      accentStrong: palette.slate[950],
      text: palette.slate[900],
    },
  },
  coach: {
    background: palette.violet[50],
    border: palette.violet[100],
    accent: palette.violet[600],
    accentStrong: palette.violet[700],
  },
  /**
   * Canonical navy "Material" dashboard palette. This is the union of the
   * near-identical palettes previously redeclared by the student home,
   * parent home, teacher dashboard, profile/settings, auth, assignment
   * detail, and progress screens. Feature screens migrate to these roles
   * instead of redeclaring local copies.
   */
  dashboard: {
    background: "#F8F9FF",
    card: "#FFFFFF",
    cardTranslucent: "rgba(255, 255, 255, 0.86)",
    error: "#BA1A1A",
    errorContainer: "#FFDAD6",
    glass: "rgba(255, 255, 255, 0.8)",
    inverseOnSurface: "#EAF1FF",
    inverseSurface: "#213145",
    inverseText: "#FFFFFF",
    onErrorContainer: "#93000A",
    onPrimary: "#FFFFFF",
    onPrimaryContainer: "#A5BDFF",
    onSecondary: "#FFFFFF",
    onSecondaryContainer: "#00714D",
    onSurface: "#0B1C30",
    onSurfaceVariant: "#434653",
    outline: "#737784",
    outlineVariant: "#C3C6D5",
    primary: "#00327D",
    primaryContainer: "#0047AB",
    primaryFixed: "#DAE2FF",
    primarySoft: "rgba(0, 50, 125, 0.18)",
    primarySubtle: "rgba(0, 50, 125, 0.05)",
    secondary: "#006C49",
    secondaryContainer: "#6CF8BB",
    secondaryContainerSoft: "rgba(108, 248, 187, 0.3)",
    secondaryFixed: "#6FFBBE",
    secondaryFixedDim: "#4EDEA3",
    surface: "#F8F9FF",
    surfaceContainer: "#E5EEFF",
    surfaceContainerHigh: "#DCE9FF",
    surfaceContainerHighest: "#D3E4FE",
    surfaceContainerLow: "#EFF4FF",
    surfaceContainerLowest: "#FFFFFF",
    surfaceDim: "#CBDBF5",
    surfaceLowest: "#FFFFFF",
    surfaceVariant: "#D3E4FE",
    tertiaryContainer: "#FFDDB8",
    tertiaryFixed: "#FFDDB8",
    tertiaryFixedDim: "#FFB95F",
    tertiaryText: "#653E00",
  },
  overlay: {
    scrim: "rgba(15, 23, 42, 0.42)",
  },
} as const;

export type ColorTokens = typeof colors;
