/**
 * WriterHabit base palette, matching the docs/screens design references.
 * Scale names are historical: "slate" is the warm stone/ink neutral ramp,
 * "blue" is the forest-green primary action hue, "amber" is the brand
 * gold, "red" is the clay error hue, "teal" is the parent/teacher accent,
 * and "violet" is the deep sage used for coach moments.
 */
export const palette = {
  white: "#FFFFFF",
  black: "#000000",
  slate: {
    50: "#FBF9F5",
    100: "#F1EDE4",
    200: "#E9E3DA",
    300: "#DDD5C8",
    400: "#A89C8A",
    500: "#857C70",
    600: "#6B6258",
    700: "#57504A",
    800: "#3A352F",
    900: "#2C2825",
    950: "#1F1C19",
  },
  blue: {
    50: "#EEF2EC",
    100: "#DFF0E3",
    200: "#D6E1D6",
    500: "#4D7E5D",
    600: "#3F6B4F",
    700: "#34593F",
    800: "#2C4A35",
    900: "#243D2C",
  },
  teal: {
    50: "#EAF2EF",
    100: "#D5E0D9",
    500: "#2F9E8F",
    600: "#2C7A6E",
    700: "#25665C",
  },
  green: {
    50: "#E5F2E8",
    100: "#DFF0E3",
    600: "#3F6B4F",
    700: "#34593F",
  },
  amber: {
    50: "#FBF3E6",
    100: "#EFE0C4",
    500: "#C8973F",
    700: "#8A6A2C",
  },
  red: {
    50: "#F8E8E3",
    100: "#F1D6CD",
    600: "#B3543F",
    700: "#A8412E",
  },
  violet: {
    50: "#EEF2EC",
    100: "#D6E1D6",
    600: "#3A4A3E",
    700: "#2F3D33",
  },
} as const;

export const colors = {
  background: {
    app: "#F6F3EE",
    canvas: "#FBF9F5",
    surface: palette.white,
    surfaceRaised: "#FDFCFA",
    subtle: palette.blue[50],
    inverse: palette.slate[950],
  },
  text: {
    primary: palette.slate[900],
    secondary: palette.slate[700],
    muted: palette.slate[500],
    inverse: palette.white,
    link: palette.blue[700],
    danger: palette.red[700],
    success: palette.green[700],
  },
  border: {
    default: palette.slate[200],
    strong: palette.slate[300],
    focus: palette.blue[500],
    danger: palette.red[600],
    success: palette.green[600],
    warning: palette.amber[500],
  },
  action: {
    primary: {
      background: palette.blue[700],
      pressed: palette.blue[800],
      foreground: palette.white,
      disabledBackground: palette.slate[300],
      disabledForeground: palette.slate[600],
    },
    secondary: {
      background: palette.white,
      pressed: palette.blue[50],
      foreground: palette.blue[800],
      border: palette.blue[200],
      disabledBackground: palette.slate[100],
      disabledForeground: palette.slate[500],
    },
    ghost: {
      background: "transparent",
      pressed: palette.slate[100],
      foreground: palette.slate[800],
      disabledForeground: palette.slate[400],
    },
    danger: {
      background: palette.red[600],
      pressed: palette.red[700],
      foreground: palette.white,
      disabledBackground: palette.red[100],
      disabledForeground: palette.red[700],
    },
  },
  feedback: {
    info: {
      background: palette.blue[50],
      border: palette.blue[100],
      pressed: palette.blue[100],
      text: palette.blue[900],
      icon: palette.blue[700],
    },
    success: {
      background: palette.green[50],
      border: palette.green[100],
      pressed: palette.green[100],
      text: palette.green[700],
      icon: palette.green[600],
    },
    warning: {
      background: palette.amber[50],
      border: palette.amber[100],
      pressed: palette.amber[100],
      text: palette.amber[700],
      icon: palette.amber[500],
    },
    error: {
      background: palette.red[50],
      border: palette.red[100],
      pressed: palette.red[100],
      text: palette.red[700],
      icon: palette.red[600],
    },
    neutral: {
      background: palette.slate[50],
      border: palette.slate[200],
      pressed: palette.slate[100],
      text: palette.slate[700],
      icon: palette.slate[500],
    },
  },
  gradeBand: {
    elementary: {
      background: "#F6F3EE",
      surface: "#FFFFFF",
      accent: palette.teal[500],
      accentStrong: palette.teal[700],
      text: palette.slate[900],
    },
    middle: {
      background: "#F6F3EE",
      surface: "#FFFFFF",
      accent: palette.blue[600],
      accentStrong: palette.blue[800],
      text: palette.slate[900],
    },
    high: {
      background: "#F6F3EE",
      surface: "#FFFFFF",
      accent: palette.slate[800],
      accentStrong: palette.slate[950],
      text: palette.slate[900],
    },
  },
  coach: {
    background: palette.violet[50],
    border: palette.violet[100],
    accent: palette.violet[600],
    accentStrong: palette.violet[700],
  },
  /**
   * Canonical WriterHabit "paper & forest" dashboard palette, matching the
   * design references in docs/screens (warm cream surfaces, forest-green
   * primary, gold tertiary). This is the union of the near-identical
   * palettes previously redeclared by the student home, parent home,
   * teacher dashboard, profile/settings, auth, assignment detail, and
   * progress screens. Feature screens migrate to these roles instead of
   * redeclaring local copies.
   */
  dashboard: {
    background: "#F6F3EE",
    backgroundOverlay: "rgba(246, 243, 238, 0.95)",
    card: "#FFFFFF",
    cardTranslucent: "rgba(255, 255, 255, 0.86)",
    error: "#B3543F",
    errorContainer: "#F8E8E3",
    glass: "rgba(255, 255, 255, 0.8)",
    glassFaint: "rgba(255, 255, 255, 0.12)",
    inverseOnSurface: "#EFECE4",
    inverseSurface: "#35583F",
    inverseSurfaceHigh: "#2C4A35",
    inverseText: "#FFFFFF",
    onErrorContainer: "#A8412E",
    onPrimary: "#FFFFFF",
    onPrimaryContainer: "#A9C4B1",
    onSecondary: "#FFFFFF",
    onSecondaryContainer: "#34593F",
    onSurface: "#2C2825",
    onSurfaceVariant: "#6B6258",
    outline: "#857C70",
    outlineFaint: "rgba(214, 205, 190, 0.45)",
    outlineVariant: "#E9E3DA",
    primary: "#34593F",
    primaryContainer: "#3F6B4F",
    primaryFixed: "#DFF0E3",
    primaryFixedBorder: "#9EC0A8",
    primaryMuted: "rgba(52, 89, 63, 0.4)",
    primarySoft: "rgba(52, 89, 63, 0.18)",
    primarySubtle: "rgba(52, 89, 63, 0.05)",
    secondary: "#3F6B4F",
    secondaryContainer: "#DFF0E3",
    secondaryContainerSoft: "rgba(223, 240, 227, 0.5)",
    secondaryFixed: "#DFF0E3",
    secondaryFixedDim: "#9EC0A8",
    secondarySoft: "rgba(63, 107, 79, 0.2)",
    surface: "#F6F3EE",
    surfaceContainer: "#F1EDE4",
    surfaceContainerHigh: "#ECE7DD",
    surfaceContainerHighest: "#E7E1D6",
    surfaceContainerLow: "#FBF9F5",
    surfaceContainerLowest: "#FFFFFF",
    surfaceDim: "#E3DFD5",
    surfaceLowest: "#FFFFFF",
    surfaceVariant: "#ECE7DF",
    tertiaryContainer: "#F9F0DC",
    tertiaryFixed: "#F1ECD9",
    tertiaryFixedDim: "#D9AD5B",
    tertiaryText: "#8A6A2C",
  },
  /**
   * Onboarding flow palette, previously hardcoded across the onboarding
   * step frame and selection screens. The "navy" role now carries the
   * forest-green brand primary from the docs/screens design language.
   */
  onboarding: {
    navy: "#34593F",
    ink: "#1F1C19",
    subtitle: "#57504A",
    surface: "#FFFFFF",
    dotInactive: "#D6E1D6",
    buttonShadow: "#1E3325",
    selectedBackground: "#EEF2EC",
    cardBorder: "#DDD5C8",
    iconBubble: "#DFF0E3",
    checkBorder: "#D6CFC2",
    screenBackground: "#F6F3EE",
    success: "#3F6B4F",
    checkBorderSelected: "#9EC0A8",
    previewCard: "#DFF0E3",
    previewBorder: "#9EC0A8",
    iconBubbleSoft: "#EEF2EC",
    label: "#57504A",
    avatarBorder: "#D6E1D6",
    quoteBorder: "#E9E3DA",
    cardShadow: "#2C2825",
  },
  overlay: {
    scrim: "rgba(44, 40, 37, 0.42)",
  },
} as const;

export type ColorTokens = typeof colors;
