export * from "./ai";
export * from "./audit";
export { assignmentEndpoints } from "./assignments/assignments.controller";
export { authEndpoints } from "./auth/auth.controller";
export * from "./canvas/canvas.contracts";
export { CanvasService, canvasEndpoints } from "./canvas/canvas.service";
export * from "./notifications";
export { onboardingEndpoints } from "./onboarding/onboarding.controller";
export { parentEndpoints } from "./parents/parents.controller";
export { progressEndpoints } from "./progress/progress.controller";
export { studentEndpoints } from "./students/students.controller";
export { submissionEndpoints } from "./submissions/submissions.controller";
export { subscriptionEndpoints } from "./subscriptions/subscriptions.controller";
export { teacherEndpoints } from "./teachers/teachers.controller";
